name: IINACT-TC build & release 

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Download Dalamud
      shell: pwsh
      run: |
        $release = Invoke-RestMethod -Uri "https://api.github.com/repos/PlusoneChiang/Dalamud/releases/latest"
        $url = ($release.assets | Where-Object { $_.name -like "*.zip" } | Select-Object -First 1).browser_download_url
        Invoke-WebRequest -Uri $url -OutFile latest.zip
        Expand-Archive -Force latest.zip /tmp/dalamud
    - name: Build
      run: dotnet build -c release
    - name: Pack
      shell: pwsh
      run: |
        $build = Get-Content -Raw -Path IINACT/IINACT.json | ConvertFrom-Json
        $repo = Get-Content -Raw -Path repo.json | ConvertFrom-Json | Select-Object -First 1
        mkdir output
        Copy-Item -Path "IINACT/bin/Release/win-x64/IINACT/*" -Destination "output/" -Recurse -Force
        if(Test-Path -Path "output/IINACT.json"){
          Remove-Item -Path "output/IINACT.json"
        }
        $build | ConvertTo-Json | Set-Content 'output/IINACT.json'
        Compress-Archive -Path "output/*" -DestinationPath 'IINACT.zip'
        if (-not (Test-Path -Path "IINACT.zip")) {
            throw "File IINACT.zip does not exist."
        }
        Write-Output "RELEASE_VERSION=$($build.AssemblyVersion)" >> $env:GITHUB_ENV
        $repo.AssemblyVersion = $repo.TestingAssemblyVersion = $build.AssemblyVersion
        $repo.DownloadLinkInstall = 'https://github.com/PlusoneChiang/IINACT/releases/download/v' + $repo.AssemblyVersion + '/IINACT.zip'
        $repo.DownloadLinkTesting =  'https://github.com/PlusoneChiang/IINACT/releases/download/v' + $repo.TestingAssemblyVersion + '/IINACT.zip'
        $repo.DownloadLinkUpdate = $repo.DownloadLinkInstall
        $repo | ConvertTo-Json | % { "[`n" + $_ + "`n]" } | Set-Content 'repo.json'
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        name: v${{ env.RELEASE_VERSION }}
        tag_name: v${{ env.RELEASE_VERSION }}
        files: |
          IINACT.zip
    - name: Commit repo.json
      run: |
        git config --global user.name "Actions User"
        git config --global user.email "actions@github.com"
        git fetch origin tc/api13_net9
        git checkout tc/api13_net9
        git add repo.json
        git commit -m "[CI] updating repo.json for ${{ env.RELEASE_VERSION }}" || true
        git push origin tc/api13_net9
